name: Main

on:
  push:
    branches:
      - master
  #schedule:
  #  - cron: '0 0 1,5,10,15,20,25 * *'

jobs:

  build-publish-trigger:
    runs-on: ubuntu-latest
    env:
      DOCKER_PASS: ${{ secrets.DOCKER_FOUNDATION_PASS }}
      DOCKER_USER: ${{ secrets.DOCKER_FOUNDATION_USER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image, test it, push it dockerhub, notify dependents
        run: ./pipe_build_up_test.sh