name: Main

on:
  push:
    branches:
      - master

jobs:

  build-publish-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image, test it, push it dockerhub, notify dependents
        run: ./pipe_build_up_test.sh